JariBakken: Cast to Throwable instead of Exception (to handle NoClassDefFoundError).
git-svn-id: http://selenium.googlecode.com/svn/trunk@9508 07704840-8298-11de-bf8c-fd130f914ac9